# Generated by Django 4.2.3 on 2023-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auctin',
            field=models.BooleanField(default=False, help_text='Отметьте, если торг уместен', verbose_name='торг'),
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
